[tool.poetry]
name = "mainframe-orchestra"
version = "1.0.0"
description = "Mainframe-Orchestra is a lightweight, open-source agentic framework for building LLM based pipelines and self-orchestrating multi-agent teams"
authors = [
    "Mainframe Computer Inc. <hi@mainfra.me>",
    "Philippe Andre Page <philippe@mainfra.me>"
]
readme = "README.md"
packages = [{ include = "mainframe_orchestra", from = "src" }]
license = "Apache 2.0"
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: Apache Software License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
]

[tool.poetry.dependencies]
python = "^3.10"
requests = ">=2.32.0"  # Fix for credential leak vulnerability
pydantic = ">=2.0"
litellm = "*"
beautifulsoup4 = "*"
tqdm = "*"
python-dotenv = "*"
PyYAML = "*"
lxml = "*"
numpy = "*"
faiss-cpu = "*"
pinecone = "*"
sentence_splitter = "*"
igraph = "*"
leidenalg = "*"
fake-useragent = "*"
tzdata = "^2024.2"
braintrust = "*"
mcp = ">=1.7.0"  # Fix for MCP vulnerabilities - use newer version
fastmcp = ">=2.3.0"  # Fix for FastMCP vulnerabilities - use newer version
pillow = ">=11.0.0"  # Fix for BCn encoding buffer overflow
protobuf = ">=5.29.0"  # Fix for protobuf DoS vulnerability
urllib3 = ">=2.2.3"  # Fix for redirect control issues
aiohttp = ">=3.11.20"  # Fix for parsing vulnerability

[tool.poetry.extras]
langchain_tools = [
    "langchain-core",
    "langchain-community",
    "langchain-openai"
]
matplotlib_tools = [
    "matplotlib"
]
fred_tools = [
    "fredapi",
    "pandas"
]
audio_tools = [
    "pygame",
    "elevenlabs"
]
stripe_tools = [
    "stripe-agent-toolkit"
]

[tool.poetry.dependencies.langchain-core]
version = "*"
optional = true

[tool.poetry.dependencies.langchain-community]
version = "*"
optional = true

[tool.poetry.dependencies.langchain-openai]
version = "*"
optional = true

[tool.poetry.dependencies.matplotlib]
version = "*"
optional = true

[tool.poetry.dependencies.stripe-agent-toolkit]
version = "*"
optional = true

[tool.poetry.dependencies.elevenlabs]
version = "*"
optional = true

[tool.poetry.group.dev.dependencies]
pytest = ">=8.0.0,<9.0.0"
black = ">=23.0,<25.0"
isort = ">=5.0,<6.0"
mypy = ">=1.0,<2.0"
ruff = "^0.8.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.urls]
"Homepage" = "https://github.com/mainframecomputer/orchestra/"
"Bug Tracker" = "https://github.com/mainframecomputer/orchestra/issues"
"Documentation" = "https://orchestra.org"

[tool.black]
line-length = 100
target-version = ['py310']

[tool.isort]
profile = "black"
line_length = 100

[tool.mypy]
python_version = "3.10"
strict = true
ignore_missing_imports = true

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q"
testpaths = [
    "tests",
]

[tool.ruff]
line-length = 100
